### ISSUE TITLE
Track deal status

### ISSUE THREAD

**Issue by jennijuju** [lotus-web3/client-contract#29]
The goal is to get the deal status, where a deal can be in 3/4 states 
- proposal created 
- proposal published 
- proposal publish failed (optional)
- deal fully activated (included in a sector)

store status on chain in contract, rough notes (see team feedback in the ticket): 
  - add  `mapping(bytes => int64) public pieceStatus; // pieceCID -> status`
  - set `status` to be `0` when the deal proposal is submitted 
  - set `status` to be `1` when the deal is fully published 
  - set `status` to be `-1` when the deal publish failed 
  - set `status` to be `2` when the deal is activated 
    - To get this info:
      - In the contract: add the `GetDealActivation` call 
      - script: calling `GetDealActivation` periodically (can be done in batch)

**Comment by raulk** [comment]
Can use a Solidity enum for `status`.

I would be pro adding the status tracking to the reference client contract.

1. We identified attack vectors that would be solved by tracking the status of deals in a local state machine and allowing actions based on it, e.g. SP hoarding all deals by publishing them, and failing to follow through with sealing. This could be counteracted by tracking to epoch at which the market notifies a deal, then offering another method invokable by the miner to signal completion (which then goes to the market actor to validate the deal is activated). If the method is not called within a specific time window (e.g. N epochs, configurable), the deal expires, and anybody call the contract to transition the deal to expired, withdraw it from the miner, return it to the claimable pool, and potentially penalise the miner (or remove it from the allowlist after a number of failures).
2. It is a generally useful feature since I expect adopters of this starter pack will eventually want to build features that reward miners via tokens, bump up scores, or perform some other kind of action on successful completion of details (or failure to do so).

**Comment by raulk** [comment]
I would use this opportunity to revisit the state tracking of pieces and deal proposals. I suspect a single map modelling a state machine would be cleaner, instead of three maps, all of which are keyed by the commP:

```solidity
    mapping(bytes => ProposalIdSet) public pieceToProposal; // commP -> dealProposalID
    mapping(bytes => ProviderSet) public pieceProviders; // commP -> provider
    mapping(bytes => uint64) public pieceDeals; // commP -> deal ID
```

**Comment by aashidham** [comment]
The best DX experience is to have deal activation explicitly called out as a dispatch method. If we do plan to do this onchain, it would be ideal to structure as a receiver hook that notifies the contract once the deal is activated. 

Having to poll for a change in deal state will eventually need to be moved to an async model, so why not do it correctly from the beginning?

This approach seems to be missing from option 1.

**Comment by scotthconner** [comment]
Here's the technical scope for the tooling aspects:

What we need inside the solidity contract:
* A registry set of all proposal IDs, and an interface of `function getProposals() public view returns (bytes32[] memory) `. This would return an ever-increasing list of keccak256 GUIDs generated from the `makeDealProposal` flow. This helps us scrape and build the data-view easily without having to aggregate an event-stream off of an RPC provider.  Also, for those GUIDs, we should be using `encode` and not `encodePacked` as a general GUID-generation best practice. 
* An extension of the existing deal struct to hold the flow state, also to prevent aggregation requirements. These need to be appropriately wired in the API methods. Because this is holding FST state, we need to also begin looking at security and re-entrancy. Always check the appropriate state first-thing during execution, and mutate the state as the last step. Sending FIL to the message sender, or any untrusted code opens a window for the receiver to re-enter your code.
* We also need to ensure that `getDealProposal` properly seralizes all of the necessary data to introspect a single deal proposal.

What we need as hardhat tasks:
* **propose-find**: A task that calls `getProposals()` and stores the entire list in a local file.
* **propose-look**: A task that calls `getDealProposal()` and displays the deal's state to the terminal.
* **propose-scape**: Uses an output file from **propose-find** as input to continually call and store the results of `getDealProposal()` into individual files like `deal-{PROPOSAL_ID}-state.json`.
* **propose-analyze**: Uses all `deal-*-state.json` to aggregate a unified reporting view (deal count, deal state distribution, datacap and fund management status, time-to-close, total-amounts-paid, etc).

In total, this is about 2-3 days total worth of effort.

**Comment by raulk** [comment]
> The best DX experience is to have deal activation explicitly called out as a dispatch method. If we do plan to do this onchain, it would be ideal to structure as a receiver hook that notifies the contract once the deal is activated.
> 
> Having to poll for a change in deal state will eventually need to be moved to an async model, so why not do it correctly from the beginning?
> 
> This approach seems to be missing from option 1.

FIP discussion needed ;-)

**Comment by jennijuju** [comment]
> The best DX experience is to have deal activation explicitly called out as a dispatch method. If we do plan to do this onchain, it would be ideal to structure as a receiver hook that notifies the contract once the deal is activated.

We(zen/anorth)  have ideas on how to approach this but would be nv20 and above on timeline.

**Comment by jennijuju** [comment]
> I would use this opportunity to revisit the state tracking of pieces and deal proposals. I suspect a single map modelling a state machine would be cleaner, instead of three maps, all of which are keyed by the commP:
> 
> ```solidity
>     mapping(bytes => ProposalIdSet) public pieceToProposal; // commP -> dealProposalID
>     mapping(bytes => ProviderSet) public pieceProviders; // commP -> provider
>     mapping(bytes => uint64) public pieceDeals; // commP -> deal ID
> ```

I agree.

**Comment by jennijuju** [comment]
While the discussion in the tickets is exactly what I was hoping for, tho  i do believe the proposed solutions are out of the scope for this .storage contract (due to time constraints. ) 
I do agree that we should do a minimal version with solidity enum and simplify the maps for the base client contract - so imma gonna transfer this issue over so we can work on that as a part of the client contract enhancement.

If the implementation is completed and tested before EOW, we can consider adapting it for the .storage contract next week!

**Comment by shrenujbansal** [comment]
> set status to be -1 when the deal publish failed

What are we trying to indicate to the user via this state?
Its possible that deal publish can fail from one miner but succeed from another, so it might not mean that the user needs to replace/scrap this deal

**Comment by jennijuju** [comment]
> > set status to be -1 when the deal publish failed
> 
> What are we trying to indicate to the user via this state? Its possible that deal publish can fail from one miner but succeed from another, so it might not mean that the user needs to replace/scrap this deal

Invalid deal proposal - don’t try again. It’s more for developers to monitoring proposal errors and remove accordingly

**Comment by shrenujbansal** [comment]
Done https://github.com/lotus-web3/client-contract/pull/35

**Comment by aashidham** [comment]
Closing as done
